"""Run and expose one real Genesis experiment for the local dashboard."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
from time import time
from uuid import uuid4

from .local_llm import plan_with_local_qwen, validated_task_plan
from .models import ActionType
from .spatial_tasks import build_room_grid, generate_task


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RUN_ROOT = Path(os.getenv("RADEONHOME_RUN_ROOT", PROJECT_ROOT / "outputs" / "dashboard_runs"))
REFERENCE_ROOT = Path(os.getenv("RADEONHOME_REFERENCE_ROOT", "/persistent/projects/reference-franka"))
_runs: dict[str, dict] = {}


PHYSICAL_SEED_BY_OBJECT = {
    "trash": 20260707,
    "keys": 20260703,
}


def physical_task_for_instruction(instruction: str) -> tuple[int, str, dict]:
    """Use Qwen's validated semantic plan to select an executable scene."""

    language_backend = plan_with_local_qwen(instruction)
    plan = validated_task_plan(instruction, language_backend["task_plan"])
    if len(plan.steps) != 1:
        raise ValueError("Run one physical pick-and-place instruction at a time.")
    step = plan.steps[0]
    if step.action is not ActionType.PICK_AND_PLACE or step.object_id not in PHYSICAL_SEED_BY_OBJECT:
        raise ValueError("Physical dashboard run currently supports trash or keys pick-and-place tasks.")
    return PHYSICAL_SEED_BY_OBJECT[step.object_id], step.object_id, language_backend


def start_physical_run(*, instruction: str, object_profile: str = "parcel_small") -> dict:
    """Start one continuous Genesis physical-contact run in a unique directory."""

    if not REFERENCE_ROOT.is_dir():
        raise RuntimeError(f"Genesis reference assets unavailable: {REFERENCE_ROOT}")
    seed, semantic_object_id, language_backend = physical_task_for_instruction(instruction)
    run_id = f"run-{int(time())}-{uuid4().hex[:8]}"
    output_dir = RUN_ROOT / run_id
    output_dir.mkdir(parents=True, exist_ok=False)
    log_path = output_dir / "console.log"
    command = [
        sys.executable, "-m", "radeon_home.mjcf_mobile_pipeline",
        "--reference-root", str(REFERENCE_ROOT),
        "--output-dir", str(output_dir),
        "--seed", str(seed),
        "--object-profile", object_profile,
        "--carry-mode", "lifted",
        "--navigation-steps", "25",
        "--transport-steps", "80",
        "--video-stride", "12",
    ]
    log_handle = log_path.open("w", encoding="utf-8")
    process = subprocess.Popen(
        command, cwd=PROJECT_ROOT, stdout=log_handle, stderr=subprocess.STDOUT
    )
    _runs[run_id] = {
        "run_id": run_id,
        "status": "running",
        "started_at": time(),
        "output_dir": output_dir,
        "process": process,
        "log_handle": log_handle,
        "command": command,
        "instruction": instruction,
        "semantic_object_id": semantic_object_id,
        "language_backend": language_backend,
    }
    return describe_run(run_id)


def describe_run(run_id: str) -> dict:
    """Return only files and measurements generated by that real run."""

    state = _runs.get(run_id)
    if state is None:
        raise KeyError(run_id)
    process = state["process"]
    return_code = process.poll()
    output_dir: Path = state["output_dir"]
    if return_code is None:
        live_status_path = output_dir / "live_status.json"
        live_status = (
            json.loads(live_status_path.read_text(encoding="utf-8"))
            if live_status_path.is_file()
            else {}
        )
        return {
            "run_id": run_id,
            "status": "running",
            "started_at": state["started_at"],
            "instruction": state["instruction"],
            "semantic_object_id": state["semantic_object_id"],
            "language_backend": state["language_backend"],
            "live_status": live_status,
            "live_rgb_url": (
                f"/runs/{run_id}/live_rgb.jpg" if (output_dir / "live_rgb.jpg").is_file() else None
            ),
            "live_depth_url": (
                f"/runs/{run_id}/live_depth.png" if (output_dir / "live_depth.png").is_file() else None
            ),
        }
    if not state["log_handle"].closed:
        state["log_handle"].close()
    result_path = output_dir / "mobile_mjcf_pipeline_result.json"
    manifest_path = output_dir / "artifact_manifest.json"
    if return_code != 0 or not result_path.is_file() or not manifest_path.is_file():
        return {
            "run_id": run_id,
            "status": "failed",
            "return_code": return_code,
            "language_backend": state["language_backend"],
            "log_url": f"/runs/{run_id}/console.log",
        }
    result = json.loads(result_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    artifacts = {
        "video_url": f"/runs/{run_id}/{manifest['full_run_video']}",
        "rgb_key_frame_urls": [f"/runs/{run_id}/{item}" for item in manifest["key_frames"]],
        "depth_key_frame_urls": [f"/runs/{run_id}/{item}" for item in manifest.get("depth_key_frames", [])],
        "result_url": f"/runs/{run_id}/mobile_mjcf_pipeline_result.json",
        "log_url": f"/runs/{run_id}/console.log",
    }
    return {
        "run_id": run_id,
        "status": "completed",
        "instruction": state["instruction"],
        "semantic_object_id": state["semantic_object_id"],
        "language_backend": state["language_backend"],
        "result": result,
        "artifacts": artifacts,
    }


def resolve_artifact(run_id: str, filename: str) -> Path:
    """Resolve a dashboard artifact without allowing path traversal."""

    state = _runs.get(run_id)
    if state is None or Path(filename).name != filename:
        raise KeyError(run_id)
    target = state["output_dir"] / filename
    if not target.is_file():
        raise FileNotFoundError(filename)
    return target
